title: 👋 Hi, I’m Swati Mirashi
description: My goal is to analyze data, uncover insights, and deliver results that create real business impact, while continuously learning and growing as a data professional...
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
